# Generated by Django 5.2 on 2025-04-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_redessociais_email_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='redessociais',
            name='x',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
