# Generated by Django 5.2 on 2025-04-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_redessociais_x'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
