# Generated by Django 5.2 on 2025-04-08 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_videosobre'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosobre',
            name='data_adicionado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videosobre',
            name='url_video',
            field=models.URLField(verbose_name='Link do YouTube'),
        ),
    ]
