# Generated by Django 5.2 on 2025-04-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_videosobre_data_adicionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='video_viagens',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
