# Generated by Django 5.2 on 2025-04-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_siteconfig_imagen_png'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodEtica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='cod_etica/')),
            ],
        ),
    ]
